### ISSUE TITLE
[Frontend Migration]: User config get's overwritten

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#854]
### Domain

Frontend

### Description

I see unexplainable POST requests to `/api/user/me/` overwriting my user config, e.g. channel banner vs grid layout. Maybe as a sideffect when a component loads? The POST request resets the user config back to default.

**Comment by MerlinScheurer** [comment]
Should be fixed now.
There was an issue where the Filterbar component would send a post on page view and missing properties.
( Fixing this now we have a double GET request on this endpoint when changing anything in the filterbar, because the page needs to be revalidated to update the userMeConfig loader. which is used in the Base component, too. So either we stick with it for now or find a way to get rid of the user config request for the Base component. )

**Comment by bbilly1** [comment]
Unfortunately that still happens for me. 

Steps to reproduce:

- Got to Channel List page
- Change view style to grid
- Navigate to the channel detail page
- The POST requests gets sent once the content is loaded, there is also a 400 request first in my case, I think it's because of some timing...

I suspect the problem comes from `Filterbar.tsx` with the dependency management from the useEffect hook. 

Thinking more broadly, wouldn't it make sense to have the user config in context or in some other global state management? And then instead of fetching it basically on every page component load, only refresh it if it changes though user interaction?

I like the fact that we store that in the backend, but if that creates too many problems for us, we could also rely on browser storage alone too.

**Comment by MerlinScheurer** [comment]
Good catch 👍 

Well i should read the correct view style from the config 🤦  ( https://github.com/tubearchivist/tubearchivist/commit/d0b4f6cdbf54ae01eb72397df03479c21349751c )
This is the cause that the Filterbar thought that the config changed. 

If it breaks 2 more times, we should replace it with localStorage 😅

**Comment by bbilly1** [comment]
You got this right before. We have:

- `view_style_home`: That is how to display multiple archived videos. `home` here might not exactly be ideal, I just implemented that on the home page only first, so the name stuck even after adding that to the other video grid views. So same style should apply for the channel videos e.g. at `/channel/<channel-id>` and for the playlist videos at `/playlist/<playlist-id>`.
- `view_style_channel`: That is for multiple archived channels, e.g. at `/channel`.
- `view_style_downloads`: That's for videos in the download queue
- `view_style_playlist`: That's for multiple archived playlists, e.g. at `/playlist`.

IMO, my commit tagged here should do that, no?

**Comment by MerlinScheurer** [comment]
That's confusing 😅 
So the view style `home` should be view style `videos` ?

**Comment by bbilly1** [comment]
Yeah, should be, ideally, in a perfect world, when the dev of this project would think ahead of what will come and what might happen. :-)

In any case, I'm investigating using [zustand](https://zustand.docs.pmnd.rs/getting-started/introduction) to handle global user config and auth state. Would you be open to use that?

As currently basically on every nav event, we need to fetch the user config and fetch the auth state, when investigating the fetch requests happening, sometimes on nav event, there are multiple ping requests happening. So with a state management library like that, we could simplify that drastically.

**Comment by MerlinScheurer** [comment]
I mean its up to you, if you want to use zustand, lets try it. We could also try to use React context.
I used redux in the past.

On the topic of auth, you have to consider, that people can bookmark any page/route and jump to that page immediately, so you have to check auth anyway.
And on page navigation you either handle 403 status codes responses on every request to the backend or have the backend cause a redirection to login or do a auth request before doing anything else.

**Comment by bbilly1** [comment]
OK, this is mostly wrapped up. Config is handled with zustand now and auth state with an abstracted backend fetching function.
