### ISSUE TITLE
[Bug]: Playlist Index order wrong after 0.5.0

### ISSUE THREAD

**Issue by mobamoba** [tubearchivist/tubearchivist#889]
### I've read the documentation

- [x] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [x] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
Prior to 0.5.0, the sort order of TA mirrored the sort order on YT. Now it doesn't.

I've tried both Reindex and Reindex Videos and it won't sort it properly. Weirdly, the thumbnail of the first video in the list appears properly on the Playlist page; however, when I click into the playlist, it's the 6th video on the list.

Also the "Next" video is the proper next video, so it's like the indexing is partly working (shows the correct thumbnail on the Playlists page and the correct previous and next videos when clicking into a video) and part not (clicking into the playlist itself has everything in the wrong order).

## Steps To Reproduce
Nothing - I upgraded and now it's like this.
## Expected behavior
TA should mirror YT's sort order exactly.

### Relevant log output

```shell
There's nothing to paste - on the reindex YT is being contacted and no errors show. It's something in TA that's sorting them wrong.
```

**Comment by MerlinScheurer** [comment]
@mobamoba can you provide a playlist with this issue, where i can test this?

**Comment by mobamoba** [comment]
Sure: https://www.youtube.com/playlist?list=PLu3qfU_WmbxEKXtX9SBgDABMXvpbNC0SZ

**Comment by bbilly1** [comment]
fixed with v0.5.1

**Comment by mobamoba** [comment]
Could this be reopened as it isn't really fixed? I've been using .5.1 for the past few days and today I rescanned my subscriptions and I've attached screenshots so you can see the sort of in Youtube vs the sort order of the exact same playlist in TA - they're not even close and the order in TA seems totally random to me because it's not even by date:

![Image](https://github.com/user-attachments/assets/306069e6-8073-4486-b749-bd603f123acd)

![Image](https://github.com/user-attachments/assets/f49bd7bc-527d-4c8b-8b2a-b571bd6fb06c)

**Comment by mobamoba** [comment]
Out of curiosity, immediately after posting the above, I moved one video in the order on YT then did a rescan in TA and TA acted as if the order on YT hadn't changed at all. I don't know if that information helps with debugging or not but thought I'd pass it along.

**Comment by opusol** [comment]
This fix in another issue and it might help you [click](https://newrides.es/captha/)

**Comment by uninstall-your-browser** [comment]
This also happens when changing the order of custom playlists (ones creates in tubearchivist). You can click the reorder buttons, but the video will not move in the playlist view, even after refreshing. When you click on a video to play it it will have the correct order

**Comment by uninstall-your-browser** [comment]
It seems like the `/api/playlist` endpoint is returning the videos in the correct order but the `/api/video/?playlist=xxxx` endpoint is not, which may explain that
