### ISSUE TITLE
[Bug]: "Authentication credentials were not provided." on new browser sessions using forward authentication - no sessionid being set (0.5.2)

### ISSUE THREAD

**Issue by Jauchi** [tubearchivist/tubearchivist#973]
### I've read the documentation

- [x] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [x] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux, Kubernetes

## Describe the bug
Using forward authentication, when logging in using a new device or private Window, I get the following issue:
#### Cookies
![Image](https://github.com/user-attachments/assets/3dd39689-a35d-430a-ba66-071530d3e742)
#### Request
![Image](https://github.com/user-attachments/assets/e9dd513a-d514-431b-8a7b-363c2dc48fc8)
#### Response
![Image](https://github.com/user-attachments/assets/2fb2799e-f09f-49bd-a608-a5be26c2789b)
### Old session
Meanwhile, in an old session, the following can be found:
#### Cookies
![Image](https://github.com/user-attachments/assets/5082437b-b812-43de-aa99-ec0f14da5a7b)
#### Request
![Image](https://github.com/user-attachments/assets/091c35c8-e057-46f0-9920-c0290d5ed254)
#### Response

![Image](https://github.com/user-attachments/assets/ba568882-c484-4ce2-9205-dd76f7521017)

### Environment
```
- name: ES_URL
  value: 'redacted'
- name: TA_ENABLE_AUTH_PROXY
  value: 'true'
- name: TA_AUTH_PROXY_USERNAME_HEADER
  value: 'HTTP_X_VOUCH_USER'
- name: TA_AUTH_PROXY_LOGOUT_URL
  value: 'https://vouch-proxy.p1ng.link/logout'
- name: REDIS_CON
  value: 'redacted'
- name: DEBUG 
  value: '1'  
- name: DJANGO_DEBUG
  value: '1'  
- name: TA_HOST
  value: 'https://tubearchivist.p1ng.link'
- name: ELASTIC_USER
  value: 'redacted'
- name: ELASTIC_PASSWORD
  value: 'redacted'
- name: TZ
  value: 'Europe/Vienna'
```
## Expected behavior
New devices can log in and use the TA webinterface

### Relevant log output

```shell
INFO:     10.244.1.160:0 - "GET /api/download/?filter=pending HTTP/1.0" 403 Forbidden
Forbidden: /api/notification/
INFO:     10.244.1.160:0 - "GET /api/notification/ HTTP/1.0" 403 Forbidden
Forbidden: /api/download/
INFO:     10.244.1.160:0 - "GET /api/download/?filter=pending HTTP/1.0" 403 Forbidden
Forbidden: /api/notification/
INFO:     10.244.1.160:0 - "GET /api/notification/ HTTP/1.0" 403 Forbidden
Forbidden: /api/download/
INFO:     10.244.1.160:0 - "GET /api/download/?filter=pending HTTP/1.0" 403 Forbidden
```

### Anything else?

Thanks for the hard work, appreciated!

**Comment by Jauchi** [comment]
Hi there, thanks a lot for the quick reply.
How exactly do I downgrade to that? Manually create a new docker image and use that?

**Comment by bbilly1** [comment]
They released Django 5.2.2. Please verify that is fixed.

Either update the library manually in the container or you can test the newest unstable build.

**Comment by Jauchi** [comment]
Sorry, just bumped Django to Version `5.2.2`, still not fixed, same symptoms as described in OP - no cookies being set.
Will downgrade to `5.1.8` for the time being.

**Comment by trick77** [comment]
I just filed a bug https://code.djangoproject.com/ticket/36443#ticket to address this issue. The quick fix when using 5.2.2 is to just remove the HTTP_ prefix in the configured TA_AUTH_PROXY_USERNAME_HEADER.

**Comment by trick77** [comment]
@bbilly1 since 5.2.1 is pretty much effed up in the authentication middleware it's probably safe to upgrade to 5.2.2 even with the inconsistency.

**Comment by bbilly1** [comment]
> The quick fix when using 5.2.2 is to just remove the HTTP_ prefix in the configured TA_AUTH_PROXY_USERNAME_HEADER.

I'm not following, is that something wrong can do from our side? If so, please make a PR @trick77 .

**Comment by bbilly1** [comment]
OK, sounds you have a good handle on things. Please update the docs accordingly.

**Comment by bbilly1** [comment]
Thanks, solved with https://github.com/tubearchivist/docs/pull/63.

**Comment by oblivioncth** [comment]
Not the worst thing ever, but I got stuck on this for hours since the note for this recent change is not only in a small font footnote, but also under the `For Authentik behind NPM Proxy Manager` section. I'm not using NPM Proxy Manager so I completely disregarded the section during setup and only came to know that this detail about the header was documented once I found this issue.

It would make sense for this note to just be under the `Auth Login Modes` section in general, or at least placed as its own top-level footnote.
